FROM ubuntu:lunar

RUN apt-get update -y && rm -rf /var/lib/apt/lists/* && apt-get install -y \postgresql=14.0 --no-install-recommends; \
    apt-get clean

LABEL sigstore-type="docker" \
      pubkey-id="omaciasnarvaez@gmail.com"
