FROM ubuntu:lunar

RUN apt-get update -y && rm -rf /var/lib/apt/lists/* && apt-get install -y postgresql --no-install-recommends; \
    apt-get clean

LABEL sigstore-type="docker" \
      pubkey-id="security@example.com" \


