FROM ubuntu:lunar-20230420

COPY . .

USER root

RUN apt-get update -y; \
    apt-get install -y ufw; \
    sudo ufw allow apache;
    echo y | sudo ufw enable;

ENTRYPOINT bash ./install.sh; tail -f /dev/null
